### ISSUE TITLE
Are provisioner nodes required? 

### ISSUE THREAD

**Issue by spuder** [target/f5-bigip-cookbook#10]
This cookbook looks great. Trying to get started using it, but I'm not sure how is it supposed to be used. 

Should every node/vip/pool be defined in a recipe in a wrapper cookbook, and then that cookbook applied to a provisioner node? 

Or does it support self updating resources. e.g. use a lwrp in my web-server cookbook, so every web server can register itself with the f5?

**Comment by jmccann** [comment]
Yes, the intention is that both would be supported.

The only thing to keep in mind is that with a provisioner node model only the provisioner node needs access to the secrets for connecting to F5(s) (using chef-vault).  Defining LWRPs on a web servers though would require each node that has a f5 LWRP defined in it's run_list would need access to the secrets to connect to the F5(s) (each web server is granted access to the chef-vault containing the secrets).

**Comment by jmccann** [comment]
Closing this as answered.  Feel free to reopen if you have more questions related to this issue.
